export const COLORS = {
  primary: "#5E9EFF",
  background: "#1A1B1E",
  surface: "#2A2B2E",
  border: "#363636",
  text: "#E5E7EB",
  secondaryText: "#9CA3AF",
  success: "#10B981",
  warning: "#F59E0B",
  danger: "#EF4444",
  disabled: "#4B5563",
  white: "oklch(.928 .006 264.531)",
  gray: "oklch(.92 .004 286.32)",
  yellow: "oklch(.905 .182 98.111)",
  green: "oklch(.845 .143 164.978)",
  progressLow: "#EF4444",
  progressMed: "#F59E0B",
  progressHigh: "#10B981",
  progressExceed: "#4B5563",
  hourModel: "#61DAFB",
  dailyModel: "#9F7AEA",
  weeklyModel: "#10B981",
  monthlyModel: "#F472B6",
};

export const STYLE = {
  borderRadius: "12px",
  boxShadow:
    "0 4px 6px -1px rgba(0, 0, 0, 0.2), 0 2px 4px -1px rgba(0, 0, 0, 0.1)",
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
  },
  textSize: {
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
  },
  lineHeight: {
    xs: "calc(1/.75)",
    sm: "calc(1.25/.875)",
    md: "1.5",
  },
};

export const TIME_WINDOWS = {
  hour3: 3 * 60 * 60 * 1000,
  hour5: 5 * 60 * 60 * 1000,
  daily: 24 * 60 * 60 * 1000,
  weekly: 7 * 24 * 60 * 60 * 1000,
  monthly: 30 * 24 * 60 * 60 * 1000,
};

export const DEFAULT_UNKNOWN_MODEL_CONFIG = {
  quota: 10000,
  windowType: "hour3",
};

export const defaultUsageData = {
  position: { x: null, y: null },
  size: { width: 400, height: 500 },
  minimized: false,
  silentMode: false,
  progressType: "bar",
  planType: "team",
  showWindowResetTime: false,
  sharedQuotaGroups: {},
  models: {
    "gpt-5-2-pro": { requests: [], quota: 15, windowType: "monthly" },
    "gpt-5-1-pro": { requests: [], quota: 15, windowType: "monthly" },
    "gpt-5-pro": { requests: [], quota: 15, windowType: "monthly" },
    "o3-pro": { requests: [], quota: 0, windowType: "monthly" },
    "gpt-4-5": { requests: [], quota: 0, windowType: "daily" },
    "gpt-5-2-thinking": { requests: [], quota: 3000, windowType: "weekly" },
    "gpt-5-1-thinking": { requests: [], quota: 3000, windowType: "weekly" },
    "gpt-5-thinking": { requests: [], quota: 3000, windowType: "weekly" },
    o3: { requests: [], quota: 100, windowType: "weekly" },
    "gpt-5-2-instant": { requests: [], quota: 10000, windowType: "hour3" },
    "gpt-5-1": { requests: [], quota: 10000, windowType: "hour3" },
    "gpt-5": { requests: [], quota: 10000, windowType: "hour3" },
    "gpt-5-t-mini": { requests: [], quota: 10000, windowType: "hour3" },
    "o4-mini": { requests: [], quota: 300, windowType: "daily" },
    "gpt-4o": { requests: [], quota: 80, windowType: "hour3" },
    "gpt-4-1": { requests: [], quota: 500, windowType: "hour3" },
    "gpt-5-mini": { requests: [], quota: 10000, windowType: "hour3" },
  },
};

export const SHARED_GROUP_COLORS = {
  "pro-premium-shared": "#facc15",
  "pro-thinking-shared": "#34d399",
  "pro-instant-shared": "#60a5fa",
  "team-premium-shared": "#facc15",
  "edu-premium-shared": "#facc15",
  "enterprise-premium-shared": "#facc15",
  "go-thinking-shared": "#34d399",
  "k12-thinking-shared": "#34d399",
  "plus-thinking-shared": "#34d399",
  "team-thinking-shared": "#34d399",
  "edu-thinking-shared": "#34d399",
  "enterprise-thinking-shared": "#34d399",
  "free-instant-shared": "#60a5fa",
  "go-instant-shared": "#60a5fa",
  "k12-instant-shared": "#60a5fa",
  "plus-instant-shared": "#60a5fa",
  "team-instant-shared": "#60a5fa",
  "edu-instant-shared": "#60a5fa",
  "enterprise-instant-shared": "#60a5fa",
};

export const MODEL_DISPLAY_ORDER = [
  "gpt-5-2-pro",
  "gpt-5-1-pro",
  "gpt-5-pro",
  "o3-pro",
  "gpt-4-5",
  "gpt-5-2-thinking",
  "gpt-5-1-thinking",
  "gpt-5-thinking",
  "o3",
  "gpt-5-t-mini",
  "o4-mini",
  "gpt-4o",
  "gpt-4-1",
  "alpha",
  // instant 模型默认放到最下面（但仍在 gpt-5-mini 上面）
  "gpt-5-2-instant",
  "gpt-5-1",
  "gpt-5",
  // gpt-5-mini 放到最最最下面
  "gpt-5-mini",
];

export const MODEL_DISPLAY_NAME_OVERRIDES = {
  "gpt-5": "gpt-5-instant",
  "gpt-5-1": "gpt-5-1-instant",
};

export function displayModelName(modelKey) {
  return MODEL_DISPLAY_NAME_OVERRIDES[modelKey] || modelKey;
}

export const PLAN_DISPLAY_ORDER = [
  "free",
  "go",
  "k12_teacher",
  "plus",
  "team",
  "edu",
  "enterprise",
  "pro",
];

export const PLAN_CONFIGS = {
  free: {
    name: "Free",
    sharedQuotaGroups: {
      "free-instant-shared": {
        quota: 10,
        windowType: "hour5",
        displayName: "Free即时共用池",
      },
    },
    models: {
      "gpt-5-2-pro": { quota: 0, windowType: "monthly" },
      "gpt-5-1-pro": { quota: 0, windowType: "monthly" },
      "gpt-5-pro": { quota: 0, windowType: "monthly" },
      "o3-pro": { quota: 0, windowType: "monthly" },
      "gpt-4-5": { quota: 0, windowType: "daily" },
      "gpt-5-2-thinking": { quota: 1, windowType: "hour5" },
      "gpt-5-1-thinking": { quota: 1, windowType: "hour5" },
      "gpt-5-thinking": { quota: 1, windowType: "hour5" },
      o3: { quota: 0, windowType: "weekly" },
      "gpt-5-2-instant": { sharedGroup: "free-instant-shared" },
      "gpt-5-1": { sharedGroup: "free-instant-shared" },
      "gpt-5": { sharedGroup: "free-instant-shared" },
      "gpt-5-t-mini": { quota: 10, windowType: "daily" },
      "o4-mini": { quota: 0, windowType: "daily" },
      "gpt-4o": { quota: 0, windowType: "hour3" },
      "gpt-4-1": { quota: 0, windowType: "hour3" },
      "gpt-5-mini": { quota: 10000, windowType: "hour3" },
    },
  },
  go: {
    name: "Go",
    sharedQuotaGroups: {
      "go-thinking-shared": {
        quota: 10,
        windowType: "hour5",
        displayName: "Go思考共用池",
      },
      "go-instant-shared": {
        quota: 100,
        windowType: "hour5",
        displayName: "Go即时共用池",
      },
    },
    models: {
      "gpt-5-2-pro": { quota: 0, windowType: "monthly" },
      "gpt-5-1-pro": { quota: 0, windowType: "monthly" },
      "gpt-5-pro": { quota: 0, windowType: "monthly" },
      "o3-pro": { quota: 0, windowType: "monthly" },
      "gpt-4-5": { quota: 0, windowType: "daily" },
      "gpt-5-2-thinking": { sharedGroup: "go-thinking-shared" },
      "gpt-5-1-thinking": { sharedGroup: "go-thinking-shared" },
      "gpt-5-thinking": { sharedGroup: "go-thinking-shared" },
      o3: { quota: 0, windowType: "weekly" },
      "gpt-5-2-instant": { sharedGroup: "go-instant-shared" },
      "gpt-5-1": { sharedGroup: "go-instant-shared" },
      "gpt-5": { sharedGroup: "go-instant-shared" },
      "gpt-5-t-mini": { quota: 100, windowType: "daily" },
      "o4-mini": { quota: 0, windowType: "daily" },
      "gpt-4o": { quota: 0, windowType: "hour3" },
      "gpt-4-1": { quota: 0, windowType: "hour3" },
      "gpt-5-mini": { quota: 10000, windowType: "hour3" },
    },
  },
  k12_teacher: {
    name: "K12 Teacher",
    sharedQuotaGroups: {
      "k12-thinking-shared": {
        quota: 160,
        windowType: "hour3",
        displayName: "K12思考共用池",
      },
      "k12-instant-shared": {
        quota: 10000,
        windowType: "hour3",
        displayName: "K12即时共用池",
      },
    },
    models: {
      "gpt-5-2-pro": { quota: 0, windowType: "monthly" },
      "gpt-5-1-pro": { quota: 0, windowType: "monthly" },
      "gpt-5-pro": { quota: 0, windowType: "monthly" },
      "o3-pro": { quota: 0, windowType: "monthly" },
      "gpt-4-5": { quota: 0, windowType: "daily" },
      "gpt-5-2-thinking": { sharedGroup: "k12-thinking-shared" },
      "gpt-5-1-thinking": { sharedGroup: "k12-thinking-shared" },
      "gpt-5-thinking": { sharedGroup: "k12-thinking-shared" },
      o3: { quota: 0, windowType: "weekly" },
      "gpt-5-2-instant": { sharedGroup: "k12-instant-shared" },
      "gpt-5-1": { sharedGroup: "k12-instant-shared" },
      "gpt-5": { sharedGroup: "k12-instant-shared" },
      "gpt-5-t-mini": { quota: 0, windowType: "daily" },
      "o4-mini": { quota: 0, windowType: "daily" },
      "gpt-4o": { quota: 0, windowType: "hour3" },
      "gpt-4-1": { quota: 0, windowType: "hour3" },
      "gpt-5-mini": { quota: 10000, windowType: "hour3" },
    },
  },
  plus: {
    name: "Plus",
    sharedQuotaGroups: {
      "plus-thinking-shared": {
        quota: 160,
        windowType: "hour3",
        displayName: "Plus思考共用池",
      },
      "plus-instant-shared": {
        quota: 10000,
        windowType: "hour3",
        displayName: "Plus即时共用池",
      },
    },
    models: {
      "gpt-5-2-pro": { quota: 0, windowType: "monthly" },
      "gpt-5-1-pro": { quota: 0, windowType: "monthly" },
      "gpt-5-pro": { quota: 0, windowType: "monthly" },
      "o3-pro": { quota: 0, windowType: "monthly" },
      "gpt-4-5": { quota: 0, windowType: "daily" },
      "gpt-5-2-thinking": { sharedGroup: "plus-thinking-shared" },
      "gpt-5-1-thinking": { sharedGroup: "plus-thinking-shared" },
      "gpt-5-thinking": { sharedGroup: "plus-thinking-shared" },
      o3: { quota: 100, windowType: "weekly" },
      "gpt-5-2-instant": { sharedGroup: "plus-instant-shared" },
      "gpt-5-1": { sharedGroup: "plus-instant-shared" },
      "gpt-5": { sharedGroup: "plus-instant-shared" },
      "gpt-5-t-mini": { quota: 10000, windowType: "hour3" },
      "o4-mini": { quota: 300, windowType: "daily" },
      "gpt-4o": { quota: 80, windowType: "hour3" },
      "gpt-4-1": { quota: 80, windowType: "hour3" },
      "gpt-5-mini": { quota: 10000, windowType: "hour3" },
    },
  },
  team: {
    name: "Team",
    sharedQuotaGroups: {
      "team-premium-shared": {
        quota: 15,
        windowType: "monthly",
        displayName: "Team高级共用池",
      },
      "team-thinking-shared": {
        quota: 3000,
        windowType: "weekly",
        displayName: "Team思考共用池",
      },
      "team-instant-shared": {
        quota: 10000,
        windowType: "hour3",
        displayName: "Team即时共用池",
      },
    },
    models: {
      "gpt-5-2-pro": { sharedGroup: "team-premium-shared" },
      "gpt-5-1-pro": { sharedGroup: "team-premium-shared" },
      "gpt-5-pro": { sharedGroup: "team-premium-shared" },
      "o3-pro": { quota: 0, windowType: "monthly" },
      "gpt-4-5": { quota: 0, windowType: "daily" },
      "gpt-5-2-thinking": { sharedGroup: "team-thinking-shared" },
      "gpt-5-1-thinking": { sharedGroup: "team-thinking-shared" },
      "gpt-5-thinking": { sharedGroup: "team-thinking-shared" },
      o3: { quota: 100, windowType: "weekly" },
      "gpt-5-2-instant": { sharedGroup: "team-instant-shared" },
      "gpt-5-1": { sharedGroup: "team-instant-shared" },
      "gpt-5": { sharedGroup: "team-instant-shared" },
      "gpt-5-t-mini": { quota: 10000, windowType: "hour3" },
      "o4-mini": { quota: 300, windowType: "daily" },
      "gpt-4o": { quota: 80, windowType: "hour3" },
      "gpt-4-1": { quota: 500, windowType: "hour3" },
      "gpt-5-mini": { quota: 10000, windowType: "hour3" },
    },
  },
  edu: {
    name: "Edu",
    sharedQuotaGroups: {
      "edu-premium-shared": {
        quota: 15,
        windowType: "monthly",
        displayName: "Edu高级共用池",
      },
      "edu-thinking-shared": {
        quota: 3000,
        windowType: "weekly",
        displayName: "Edu思考共用池",
      },
      "edu-instant-shared": {
        quota: 10000,
        windowType: "hour3",
        displayName: "Edu即时共用池",
      },
    },
    models: {
      "gpt-5-2-pro": { sharedGroup: "edu-premium-shared" },
      "gpt-5-1-pro": { sharedGroup: "edu-premium-shared" },
      "gpt-5-pro": { sharedGroup: "edu-premium-shared" },
      "o3-pro": { quota: 0, windowType: "monthly" },
      "gpt-4-5": { quota: 0, windowType: "daily" },
      "gpt-5-2-thinking": { sharedGroup: "edu-thinking-shared" },
      "gpt-5-1-thinking": { sharedGroup: "edu-thinking-shared" },
      "gpt-5-thinking": { sharedGroup: "edu-thinking-shared" },
      o3: { quota: 100, windowType: "weekly" },
      "gpt-5-2-instant": { sharedGroup: "edu-instant-shared" },
      "gpt-5-1": { sharedGroup: "edu-instant-shared" },
      "gpt-5": { sharedGroup: "edu-instant-shared" },
      "gpt-5-t-mini": { quota: 10000, windowType: "hour3" },
      "o4-mini": { quota: 300, windowType: "daily" },
      "gpt-4o": { quota: 80, windowType: "hour3" },
      "gpt-4-1": { quota: 500, windowType: "hour3" },
      "gpt-5-mini": { quota: 10000, windowType: "hour3" },
    },
  },
  enterprise: {
    name: "Enterprise",
    sharedQuotaGroups: {
      "enterprise-premium-shared": {
        quota: 15,
        windowType: "monthly",
        displayName: "Enterprise高级共用池",
      },
      "enterprise-thinking-shared": {
        quota: 3000,
        windowType: "weekly",
        displayName: "Enterprise思考共用池",
      },
      "enterprise-instant-shared": {
        quota: 10000,
        windowType: "hour3",
        displayName: "Enterprise即时共用池",
      },
    },
    models: {
      "gpt-5-2-pro": { sharedGroup: "enterprise-premium-shared" },
      "gpt-5-1-pro": { sharedGroup: "enterprise-premium-shared" },
      "gpt-5-pro": { sharedGroup: "enterprise-premium-shared" },
      "o3-pro": { quota: 0, windowType: "monthly" },
      "gpt-4-5": { quota: 0, windowType: "daily" },
      "gpt-5-2-thinking": { sharedGroup: "enterprise-thinking-shared" },
      "gpt-5-1-thinking": { sharedGroup: "enterprise-thinking-shared" },
      "gpt-5-thinking": { sharedGroup: "enterprise-thinking-shared" },
      o3: { quota: 100, windowType: "weekly" },
      "gpt-5-2-instant": { sharedGroup: "enterprise-instant-shared" },
      "gpt-5-1": { sharedGroup: "enterprise-instant-shared" },
      "gpt-5": { sharedGroup: "enterprise-instant-shared" },
      "gpt-5-t-mini": { quota: 10000, windowType: "hour3" },
      "o4-mini": { quota: 300, windowType: "daily" },
      "gpt-4o": { quota: 80, windowType: "hour3" },
      "gpt-4-1": { quota: 500, windowType: "hour3" },
      "gpt-5-mini": { quota: 10000, windowType: "hour3" },
    },
  },
  pro: {
    name: "Pro",
    sharedQuotaGroups: {
      "pro-premium-shared": {
        quota: 100,
        windowType: "daily",
        displayName: "Pro高级共用池",
      },
      "pro-thinking-shared": {
        quota: 10000,
        windowType: "hour3",
        displayName: "Pro思考共用池",
      },
      "pro-instant-shared": {
        quota: 10000,
        windowType: "hour3",
        displayName: "Pro即时共用池",
      },
    },
    models: {
      "gpt-5-2-pro": { sharedGroup: "pro-premium-shared" },
      "gpt-5-1-pro": { sharedGroup: "pro-premium-shared" },
      "gpt-5-pro": { sharedGroup: "pro-premium-shared" },
      "o3-pro": { sharedGroup: "pro-premium-shared" },
      "gpt-4-5": { quota: 100, windowType: "daily" },
      "gpt-5-2-thinking": { sharedGroup: "pro-thinking-shared" },
      "gpt-5-1-thinking": { sharedGroup: "pro-thinking-shared" },
      "gpt-5-thinking": { sharedGroup: "pro-thinking-shared" },
      o3: { quota: 10000, windowType: "hour3" },
      "gpt-5-2-instant": { sharedGroup: "pro-instant-shared" },
      "gpt-5-1": { sharedGroup: "pro-instant-shared" },
      "gpt-5": { sharedGroup: "pro-instant-shared" },
      "gpt-5-t-mini": { quota: 10000, windowType: "hour3" },
      "o4-mini": { quota: 10000, windowType: "hour3" },
      "gpt-4o": { quota: 10000, windowType: "hour3" },
      "gpt-4-1": { quota: 10000, windowType: "hour3" },
      "gpt-5-mini": { quota: 10000, windowType: "hour3" },
    },
  },
};
